### ISSUE TITLE
iOS7 Compatibility

### ISSUE THREAD

**Issue by RobertBiehl** [mattwyskiel/LicensesKit#2]
What's the reason this pod is iOS8 only? Would it be a lot of work to enable iOS7 compatibilty?

Rob

**Comment by RobertBiehl** [comment]
Ok stupid question. Just noticed that it is written in Swift ;)

**Comment by mattwyskiel** [comment]
If you really want to use this in iOS 7, you will need to copy the files directly into your target. 

It does irk me that Apple designed frameworks to only work with iOS 8, but that's the way it is.
