### ISSUE TITLE
Publish 1.2.2 to CocoaPods

### ISSUE THREAD

**Issue by barna941** [mattwyskiel/LicensesKit#8]
Hi! I would like to use your pod via CocoaPods but the last published version is 1.2.1 which is still in Swift 2. Please publish the latest version which is compatible with Swift 3. Thanks!

**Comment by balazsgerlei** [comment]
Any update on this? @mattwyskiel Can you make this happen? Thx!

**Comment by mattwyskiel** [comment]
https://cocoapods.org/?q=licenseskit

Just made some further Swift 3 updates and published version 1.2.3.

**Comment by balazsgerlei** [comment]
Nice. Thank you!
